#ifndef _SHADER_DEFINE_COMMON_HLSL
#define _SHADER_DEFINE_COMMON_HLSL

#ifndef SHADER_USE_DEFERRED_SHADING
#define SHADER_USE_DEFERRED_SHADING			0
#endif	//SHADER_USE_DEFERRED_SHADING

#define SHADER_SHADING_MODEL_UNLIT			0x0u
#define SHADER_SHADING_MODEL_DEFAULT_LIT	0x1u

#endif	//_SHADER_DEFINE_COMMON_HLSL