#ifndef _SHADER_DEFINE_COMMON_HLSL
#define _SHADER_DEFINE_COMMON_HLSL

#ifndef SHADER_USE_DEFERRED_SHADING
#define SHADER_USE_DEFERRED_SHADING			0
#endif	//SHADER_USE_DEFERRED_SHADING

#define SHADER_SHADING_MODEL_UNLIT			0x0u
#define SHADER_SHADING_MODEL_DEFAULT_LIT	0x1u

#ifndef SHADER_USE_POSITION_INPUT
#define SHADER_USE_POSITION_INPUT			0
#endif	//SHADER_USE_POSITION_INPUT

#if (SHADER_USE_POSITION_INPUT)
#ifndef SHADER_USE_POSITION_INPUT_NUM
#define SHADER_USE_POSITION_INPUT_NUM		1
#endif	//SHADER_USE_POSITION_INPUT_NUM
#endif	//SHADER_USE_POSITION_INPUT

#ifndef SHADER_USE_NORMAL_INPUT
#define SHADER_USE_NORMAL_INPUT				0
#endif	//SHADER_USE_NORMAL_INPUT

#if (SHADER_USE_NORMAL_INPUT)
#ifndef SHADER_USE_NORMAL_INPUT_NUM
#define SHADER_USE_NORMAL_INPUT_NUM			1
#endif	//SHADER_USE_NORMAL_INPUT_NUM
#endif	//SHADER_USE_NORMAL_INPUT

#ifndef SHADER_USE_TEXCOORD_INPUT
#define SHADER_USE_TEXCOORD_INPUT			0
#endif	//SHADER_USE_TEXCOORD_INPUT

#if (SHADER_USE_TEXCOORD_INPUT)
#ifndef SHADER_USE_TEXCOORD_INPUT_NUM
#define SHADER_USE_TEXCOORD_INPUT_NUM		1
#endif	//SHADER_USE_TEXCOORD_INPUT_NUM
#endif	//SHADER_USE_TEXCOORD_INPUT

#ifndef SHADER_USE_TANGENT_INPUT
#define SHADER_USE_TANGENT_INPUT			0
#endif	//SHADER_USE_TANGENT_INPUT

#if (SHADER_USE_TANGENT_INPUT)
#ifndef SHADER_USE_TANGENT_INPUT_NUM
#define SHADER_USE_TANGENT_INPUT_NUM		1
#endif	//SHADER_USE_TANGENT_INPUT_NUM
#endif	//SHADER_USE_TANGENT_INPUT

#ifndef SHADER_USE_COLOR_INPUT
#define SHADER_USE_COLOR_INPUT				0
#endif	//SHADER_USE_COLOR_INPUT

#if (SHADER_USE_COLOR_INPUT)
#ifndef SHADER_USE_COLOR_INPUT_NUM
#define SHADER_USE_COLOR_INPUT_NUM			1
#endif	//SHADER_USE_COLOR_INPUT_NUM
#endif	//SHADER_USE_COLOR_INPUT

#ifndef SHADER_USE_SKELETON_INPUT
#define SHADER_USE_SKELETON_INPUT			0
#endif	//SHADER_USE_SKELETON_INPUT

#if (SHADER_USE_SKELETON_INPUT)
#ifndef SHADER_SKELETON_EFFECT_BONE_NUM
#define SHADER_SKELETON_EFFECT_BONE_NUM		1
#endif	//SHADER_SKELETON_EFFECT_BONE_NUM
#endif	//SHADER_USE_SKELETON_INPUT

#endif	//_SHADER_DEFINE_COMMON_HLSL