#pragma once

namespace PigeonEngine
{

#define ENGINE_RENDER_CORE_ERROR		("ENGINE_RENDER_CORE_ERROR")
#define ENGINE_READ_FILE_ERROR			("ENGINE_READ_FILE_ERROR")
#define ENGINE_ASSET_ERROR				("ENGINE_ASSET_ERROR")
#define ENGINE_SHADER_ERROR				("ENGINE_SHADER_ERROR")

};