#pragma once

namespace PigeonEngine
{

#define ENGINE_RENDER_CORE_ERROR		("ENGINE_RENDER_CORE_ERROR")
#define ENGINE_IO_FILE_ERROR			("ENGINE_IO_FILE_ERROR")
#define ENGINE_ASSET_ERROR				("ENGINE_ASSET_ERROR")
#define ENGINE_SHADER_ERROR				("ENGINE_SHADER_ERROR")
#define ENGINE_ACTOR_ERROR				("ENGINE_ACTOR_ERROR")
#define ENGINE_COMPONENT_ERROR			("ENGINE_COMPONENT_ERROR")
#define ENGINE_ARRAY_ERROR              ("ENGINE_ARRAY_ERROR")
#define ENGINE_SET_ERROR                ("ENGINE_SET_ERROR")
#define ENGINE_OCTREE_ERROR             ("ENGINE_OCTREE_ERROR")
};